### ISSUE TITLE
Could not init logging classes

### ISSUE THREAD

**Issue by RadekCap** [jkonecny12/kuki-in-docker#1]
I'm getting this error when I run run_kuki.sh:

```
Could not init logging classes. Permission errors on ~/.kuki (/home/kuki/.kuki/temp/)
ERROR: Unable to create application. Exiting
```

On Fedora 26 and X windows system.

Steps to reproduce:

1. Fedora 26, Wayland
2. sudo dnf install docker
3. sudo systemctl run docker
4. clone repository
5. run build_docker.sh
6. relogin to x window
7. run_kuki.sh

**Comment by RadekCap** [comment]
It runs fine even on Wayland after I've changed owner for .kuki folder.

`chown me .kuki/`

**Comment by jkonecny12** [comment]
Could you please write the bad permissions here. Who is the owner?

**Comment by RadekCap** [comment]
root

**Comment by jkonecny12** [comment]
I guess this will be some problem with XWayland / Xorg implementation. If it is working correctly without switching to the Xorg then I guess I won't able to do something about that.

Another thing is, most probably I will discontinued this project based on the new information from users comment:
https://mojefedora.cz/jak-zprovoznit-kuki-tv-v-dockeru/#comment-162209

In short, it looks like Netbox Kuki TV is unsupported by Netbox company. There will be replacement in the next (2018) year. Right now Kuki will work for actual registered devices only.
